jdi-testing/test-site

build_to_jdi-light.sh

This script performs test build and shows the result in browser
If user is satisfied with the result, the required js files are built and placed into jdi-light/angular folder
Run build_to_jdi-light.sh and follow the instructions.

Issue 1868: script to place modified site to jdi-light

---

angular-site/package.json
angular-site/src/app/buttons-and-indicators/button/button-types-example.css
angular-site/src/app/data-table/sort-header/sort-overview-example.css
angular-site/src/app/data-table/table/table-overview-example.css
angular-site/src/app/data-table/table/table-sticky-columns-example.css
angular-site/src/app/form-controls/datepicker/datepicker-formats-example.html
angular-site/src/app/form-controls/datepicker/datepicker-locale-example.html
angular-site/src/app/form-controls/datepicker/datepicker-moment-example.html
angular-site/src/app/layout/tab/tab-group-theme-example.css
angular-site/src/index.html
angular-site/src/main.ts
angular-site/tsconfig.json

[1876](https://github.com/jdi-testing/jdi-light/issues/1876)

1876 Agular Fix datepickers

---

angular-site/src/app/navigation/sidenav/sidenav-responsive-example.ts

Add a tiny change to https://github.com/jdi-testing/jdi-light/pull/1980 changes

Restore last Angular elements from Bottom Sheet to Tables

---

.travis.yml
angular-site/package.json
travis_automerge_to_jdi_light.sh

Following issues have been found so far:
1. **Root cause:** 'ng build --prod' fails with following message:
> ERROR in The target entry-point "@angular/material-moment-adapter" has missing dependencies:
> - moment
- Travis.yml has been modified to run ng build at test phase
- Automerge script won't proceed in case ng build fails
2. A command that created PR message failed in case PR message contained single quotes (fixed)

2028 Travis automerge problem fix

---

angular-site/src/app/form-controls/autocomplete/autocomplete-auto-active-first-option-example.html

This commit that changes id of webelement to demonstrate that change is propagated from test-site to jdi-light

2028::Test change of element id to demonstrate that automerge works

---

angular-site/src/app/form-controls/checkbox/checkbox-configurable-example.html
angular-site/src/app/form-controls/checkbox/checkbox-overview-example.html
angular-site/src/app/form-controls/slide-toggle/slide-toggle-configurable-example.html
angular-site/src/app/form-controls/slide-toggle/slide-toggle-overview-example.html

related to https://github.com/jdi-testing/jdi-light/issues/2097

Add ids to checkboxes and slide-toggles

---

angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-buffer-example.css
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-buffer-example.html
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-buffer-example.ts
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-configurable-example.html
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-determinate-example.css
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-determinate-example.html
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-determinate-example.ts
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-indeterminate-example.css
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-indeterminate-example.html
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-indeterminate-example.ts
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-query-example.css
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-query-example.html
angular-site/src/app/buttons-and-indicators/progress-bar/progress-bar-query-example.ts
angular-site/src/app/buttons-and-indicators/progress-spinner/progress-spinner-configurable-example.html
angular-site/src/app/buttons-and-indicators/progress-spinner/progress-spinner-overview-example.css
angular-site/src/app/buttons-and-indicators/progress-spinner/progress-spinner-overview-example.html
angular-site/src/app/buttons-and-indicators/progress-spinner/progress-spinner-overview-example.ts
angular-site/src/index.html
angular-site/src/main.ts

Implement https://github.com/jdi-testing/jdi-light/issues/2026

Modify spinner ang progress bars

---

angular-site/src/app/navigation/menu/menu-icons-example.css
angular-site/src/app/navigation/menu/menu-icons-example.html
angular-site/src/app/navigation/menu/menu-icons-example.ts
angular-site/src/app/navigation/menu/menu-overview-example.css
angular-site/src/app/navigation/menu/menu-overview-example.html
angular-site/src/app/navigation/menu/menu-overview-example.ts
angular-site/src/app/navigation/menu/nested-menu-example.css
angular-site/src/app/navigation/menu/nested-menu-example.html
angular-site/src/app/navigation/menu/nested-menu-example.ts

https://github.com/jdi-testing/jdi-light/issues/2126

2126 Angular elements: Add labels with selected Menu options

---

angular-site/src/app/form-controls/select/select-custom-trigger-example.html
angular-site/src/app/form-controls/select/select-disabled-example.html
angular-site/src/app/form-controls/select/select-error-state-matcher-example.html
angular-site/src/app/form-controls/select/select-form-example.html
angular-site/src/app/form-controls/select/select-hint-error-example.html
angular-site/src/app/form-controls/select/select-multiple-example.html
angular-site/src/app/form-controls/select/select-no-ripple-example.html
angular-site/src/app/form-controls/select/select-optgroup-example.html
angular-site/src/app/form-controls/select/select-overview-example.html
angular-site/src/app/form-controls/select/select-panel-class-example.html
angular-site/src/app/form-controls/select/select-reset-example.html
angular-site/src/app/form-controls/select/select-value-binding-example.html

Added ids for html select forms.

1943 add select ids

---

angular-site/src/app/popups-and-modals/snackbar/snack-bar-component-example.html
angular-site/src/app/popups-and-modals/snackbar/snack-bar-component-example.ts
angular-site/src/app/popups-and-modals/snackbar/snack-bar-overview-example.html
angular-site/src/app/popups-and-modals/snackbar/snack-bar-overview-example.ts

1965 snackbar ids

---

angular-site/src/app/layout/grid-list/grid-list-dynamic-example.html
angular-site/src/app/layout/grid-list/grid-list-overview-example.html
angular-site/src/app/layout/list/list-overview-example.html
angular-site/src/app/layout/list/list-sections-example.html

We added fewer ids than we need. We need ids for every element into lists.

tiles and items ids for lists added

---

angular-site/src/app/form-controls/select/select-error-state-matcher-example.html
angular-site/src/app/form-controls/select/select-hint-error-example.html
angular-site/src/app/form-controls/select/select-value-binding-example.html

Updated ids for select-error-state-matcher-example, select-hint-error-example and select-value-binding-example htmls.

Updated ids for select.

---

angular-site/src/app/form-controls/select/select-error-state-matcher-example.html
angular-site/src/app/form-controls/select/select-hint-error-example.html

Edited ids for select-error-state-matcher-example and select-hint-error-example htmls.

Edited ids for select.

---

angular-site/src/app/form-controls/datepicker/datepicker-overview-example.html
angular-site/src/app/form-controls/datepicker/datepicker-start-view-example.html

Added ids for datepicker-start-view-example.html and edited select-overview-example.html.

Added ids for datepicker-start-view-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-value-example.html

Added ids for datepicker-value-example.html.

Added ids for datepicker-value-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-min-max-example.html

Added ids for datepicker-min-max-example.html.

Added ids for datepicker-min-max-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-filter-example.html

Added ids for datepicker-filter-example.html.

Added ids for datepicker-filter-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-disabled-example.html

Added ids for datepicker-disabled-example.html.

Added ids for datepicker-disabled-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-touch-example.html

Added ids for datepicker-touch-example.html.

Added ids for datepicker-touch-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-api-example.html

Added ids for datepicker-api-example.html.

Added ids for datepicker-api-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-touch-example.html

Updated id for datepicker-touch-example.html.

Updated id for datepicker-touch-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-formats-example.html

Added ids for datepicker-formats-example.html.

Added ids for datepicker-formats-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-locale-example.html

Added ids for datepicker-locale-example.html.

Added ids for datepicker-locale-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-moment-example.html

Added ids for datepicker-moment-example.html.

Added ids for datepicker-moment-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-events-example.html

Added ids for datepicker-events-example.html.

Added ids for datepicker-events-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-locale-example.html

Added id for datepicker-locale-example.html.

Added id for datepicker-locale-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-locale-example.html

Edited id for datepicker-locale-example.html.

Edited id for datepicker-locale-example.html.

---

angular-site/src/app/form-controls/datepicker/datepicker-events-example.html

Edited id for datepicker-events-example.html.

Edited id for datepicker-events-example.html.

---

angular-site/src/app/buttons-and-indicators/ripples/ripple-overview-example.html

Added ids for ripple-overview-example.html

Added ids for ripple-overview-example.html

---

angular-site/src/app/layout/expansion-panel/expansion-overview-example.html
angular-site/src/app/layout/expansion-panel/expansion-steps-example.html

Added ids for expansion-overview-example and expansion-steps-example.html.

Added ids for expansion-overview-example and expansion-steps-example.html.

---

angular-site/src/app/layout/expansion-panel/expansion-steps-example.html

Edited datepicker for expansion-steps-example.html.

Edited datepicker for expansion-steps-example.html.

---

angular-site/src/app/form-controls/checkbox/checkbox-configurable-example.html
angular-site/src/app/form-controls/checkbox/checkbox-overview-example.html

Edited ids for checkbox-overview-example.html and checkbox-configurable-example.html.

Edited ids for checkbox-overview-example.html and checkbox-configurable-example.html.

---

angular-site/src/app/form-controls/checkbox/checkbox-configurable-example.html

Edited id for checkbox-configurable-example.html.

Edited id for checkbox-configurable-example.html.

---

angular-site/src/app/buttons-and-indicators/chips/chips-autocomplete-example.html
angular-site/src/app/buttons-and-indicators/chips/chips-input-example.html
angular-site/src/app/buttons-and-indicators/chips/chips-overview-example.html
angular-site/src/app/buttons-and-indicators/chips/chips-stacked-example.html

Hallo, please check the added IDs to the chips-elements.

ChipsIds added

---

angular-site/src/app/buttons-and-indicators/chips/chips-overview-example.html
angular-site/src/app/buttons-and-indicators/chips/chips-stacked-example.html

Edited id for chips-overview-example.html and chips-stacked-example.html

Edited id for chips-overview-example.html and chips-stacked-example.html

---

angular-site/src/app/layout/tree/tree-checklist-example.html
angular-site/src/app/layout/tree/tree-dynamic-example.html
angular-site/src/app/layout/tree/tree-flat-overview-example.html

add Ids for tree elements

---

pages/index.js
src/components/Accordion/Accordion.js
src/components/Accordion/Accordion.stories.js
src/components/Accordion/AccordionDetails.js
src/components/Accordion/AccordionSummary.js

https://github.com/jdi-testing/jdi-light/issues/2642

Material UI - Surfaces - Accordion

---

src/components/Links/Link.js
src/components/Links/Link.stories.js

https://github.com/jdi-testing/jdi-light/issues/2635

Added material-ui Links component

---

src/components/Switch/Switch.js
src/components/Switch/Switch.stories.js

Material UI - Switch component added

---

src/components/FloatingActionButton/Fab.js
src/components/FloatingActionButton/Fab.stories.js

Floating Action Button(Fab) component added

Material UI - Floating Action Button component added

---

src/components/ButtonGroup/ButtonGroup.js
src/components/ButtonGroup/ButtonGroup.stories.js

Material UI - Button Group component added

---

src/components/Menus/ContextMenu.js
src/components/Menus/IconsMenu.js
src/components/Menus/Menu.stories.js
src/components/Menus/MenuList.js
src/components/Menus/SelectedMenu.js
src/components/Menus/SimpleMenu.js

https://github.com/jdi-testing/jdi-light/issues/2636

Added material-ui Menus component

---

src/components/Box/Box.js
src/components/Box/Box.stories.js

Material UI - Box container added

---

src/components/Drawers/ClippedDrawer.js
src/components/Drawers/Drawers.stories.js
src/components/Drawers/MiniDrawer.js
src/components/Drawers/PermanentDrawerLeft.js
src/components/Drawers/PermanentDrawerRight.js
src/components/Drawers/PersistentDrawerLeft.js
src/components/Drawers/PersistentDrawerRight.js
src/components/Drawers/ResponsiveDrawer.js
src/components/Drawers/SwipeableTemporaryDrawer.js
src/components/Drawers/TemporaryDrawer.js

[Task - Material-UI element test page creation: Navigation - Drawer](https://github.com/jdi-testing/jdi-light/issues/2634)
Time = **1d**

Added Drawers for Material UI

---

src/components/Popover/Popover.js
src/components/Popover/Popover.stories.js

https://github.com/jdi-testing/jdi-light/issues/2659

Material UI - Utils - Popover

---

src/components/Slider/RangeSlider.js
src/components/Slider/Slider.js
src/components/Slider/Slider.stories.js
src/components/Slider/VerticalSlider.js

2627 Material UI - Slider component added

---

src/components/Paper/Paper.js
src/components/Paper/Paper.stories.js

https://github.com/jdi-testing/jdi-light/issues/2640

Material UI - Surfaces - Paper

---

src/components/TextField/TextField.js
src/components/TextField/TextField.stories.js

TextField components are added

TextField components are added

---

src/components/Grid/Grid.js
src/components/Grid/Grid.stories.js

Grid component is added

---

src/components/Button/Button.stories.js

Disabled and Outlined buttons are added

 Material UI - Button component added

---

src/components/Stepper/MobileStepper.js
src/components/Stepper/NonLinearStepper.js
src/components/Stepper/SimpleStepper.js
src/components/Stepper/Stepper.stories.js
src/components/Stepper/StepperWithOption.js

https://github.com/jdi-testing/jdi-light/issues/2637

Added material-ui Stepper component

---

src/components/TextareaAutosize/MaxHeightTextarea.js
src/components/TextareaAutosize/MinHeightTextarea.js
src/components/TextareaAutosize/TextareaAutosize.js
src/components/TextareaAutosize/TextareaAutosize.stories.js

https://github.com/jdi-testing/jdi-light/issues/2662

Added TextareaAutosize element

---

src/components/AppBar/AppBar.js
src/components/AppBar/AppBar.stories.js

2639 app bar

---

src/components/Progress/CircularDeterminate.js
src/components/Progress/CircularIndeterminate.js
src/components/Progress/CircularIntegration.js
src/components/Progress/CircularWithValueLabel.js
src/components/Progress/CustomizedProgressBars.js
src/components/Progress/DelayingAppearance.js
src/components/Progress/LinearBuffer.js
src/components/Progress/LinearDeterminate.js
src/components/Progress/LinearIndeterminate.js
src/components/Progress/LinearWithValueLabel.js
src/components/Progress/Progress.stories.js

[Task - Material-UI element test page creation: Feedback - Progress](https://github.com/jdi-testing/jdi-light/issues/2643)
Time = **4h**

Added Progress for Feedback

---

src/components/UseMediaQuery/UseMediaQuery.js
src/components/UseMediaQuery/UseMediaQuery.stories.js
src/components/UseMediaQuery/UseWidth.js

https://github.com/jdi-testing/jdi-light/issues/2664

Added useMediaQuery element

---

src/components/Transitions/Transitions.js
src/components/Transitions/Transitions.stories.js

https://github.com/jdi-testing/jdi-light/issues/2663

Material UI - Utils - Transitions

---

src/components/Modal/Modal.stories.js
src/components/Modal/ServerModal.js
src/components/Modal/SimpleModal.js
src/components/Modal/SpringModal.js
src/components/Modal/TransitionsModal.js

[Task - Material-UI element test page creation: Utils - Modal](https://github.com/jdi-testing/jdi-light/issues/2658)
Time = **2h**

Added Modal for Material UI

---

src/components/ButtonGroup/ButtonGroup.stories.js

Split Button Group (dropdown-like button group) added

Material UI - Split Button Group added

---

src/components/Badge/Badge.js
src/components/Badge/Badge.stories.js

https://github.com/jdi-testing/jdi-light/issues/2648

Added material-ui Badge component

---

src/components/Checkbox/Checkbox.js
src/components/Checkbox/Checkbox.stories.js
src/components/Checkbox/FormControl.js
src/components/Checkbox/FormControlLabel.js
src/components/Checkbox/FormGroup.js
src/components/Checkbox/FormLabel.js

Checkbox components are added

---

src/components/Popper/FakedReferencePopper.js
src/components/Popper/Popper.js
src/components/Popper/Popper.stories.js
src/components/Popper/PositionedPopper.js
src/components/Popper/SimplePopper.js
src/components/Popper/TransitionsPopper.js

https://github.com/jdi-testing/jdi-light/issues/2660

Added Popper element

---

src/components/Grid/Grid.stories.js

console errors are fixed for Grid

console errors are fixed for Grid

---

src/components/Lists/CheckboxList.js
src/components/Lists/Lists.stories.js
src/components/Lists/PinnedSubheaderList.js
src/components/Lists/SimpleList.js

Are added SimpleList, CheckboxList and PinnedSubheaderList

2653 - Material UI- added data display lists

---

src/components/Tooltip/Tooltip.js
src/components/Tooltip/Tooltip.stories.js

Material UI - Tooltip element added

---

src/components/Hidden/Hidden.js
src/components/Hidden/Hidden.stories.js

Depending on browser size showing different number of blocks - some could be hidden.

Material UI - Layout Hidden component is added(2618)

---

src/components/Dialog/AlertDialog.js
src/components/Dialog/ConfirmationDialog.js
src/components/Dialog/Dialog.js
src/components/Dialog/Dialog.stories.js
src/components/Dialog/DialogActions.js
src/components/Dialog/DialogContent.js
src/components/Dialog/FormDialog.js
src/components/Dialog/ListItemsDialog.js
src/components/Dialog/ScrollableDialog.js

https://github.com/jdi-testing/jdi-light/issues/2644

Added material-ui Dialog component

---

src/components/Table/PaginationTable.js
src/components/Table/SimpleTable.js
src/components/Table/SortingTable.js
src/components/Table/SpanningTable.js
src/components/Table/Table.js
src/components/Table/Table.stories.js

https://github.com/jdi-testing/jdi-light/issues/2654

Added material-ui Table component

---

src/components/FloatingActionButton/Fab.stories.js

Floating Action Button: component AddIcon replaced as inner tag

Console error fixes for Floating Action Button

---

src/router/index.js
src/views/AspectRatios.vue

Added Aspect Ratio element. Added route to the element in index.js

3042-Vuetify-element-page-Aspect_ratios

---

src/components/bottom_sheets/InsetBottomSheet.vue
src/components/bottom_sheets/ModelBottomSheet.vue
src/components/bottom_sheets/MusicPlayerBottomSheet.vue
src/components/bottom_sheets/OpenInListBottomSheet.vue
src/components/bottom_sheets/PersistentBottomSheet.vue
src/router/index.js
src/views/BottomSheets.vue

The Bottom sheets page is ready for a review.
Though I'm not 100% sure that it was necessary to implement Music Player and Open In List.

3050-Vuetify-element-page-Bottom_sheets

---

src/components/appbars/CollapsibleBar.vue
src/components/appbars/DenseBar.vue
src/components/appbars/ElevateScrollBar.vue
src/components/appbars/FadeImageBar.vue
src/components/appbars/HidingScrollBar.vue
src/components/appbars/ImageBar.vue
src/components/appbars/ScrollThresholdBar.vue
src/components/appbars/ToggleNavigationDrawersBar.vue
src/router/index.js
src/views/AppBar.vue

3046-Vuetify-element-page-AppBars

---

src/components/toolbars/BackgroundToolbar.vue
src/components/toolbars/CollapseToolbar.vue
src/components/toolbars/ContextualActionToolbar.vue
src/components/toolbars/DenseToolbar.vue
src/components/toolbars/ExtendedToolbar.vue
src/components/toolbars/FlexibleAndCardToolbar.vue
src/components/toolbars/FloatingWithSearchToolbar.vue
src/router/index.js
src/views/Toolbar.vue

3047-Vuetify-element-page-Toolbar

---

src/components/overlays/AbsoluteOverlay.vue
src/components/overlays/AdvancedOverlay.vue
src/components/overlays/LoaderOverlay.vue
src/components/overlays/OpacityOverlay.vue
src/components/overlays/ZIndexOverlay.vue
src/router/index.js
src/views/Overlays.vue

3091-Vuetify-element-Overlays

---

src/components/timelines/AdvancedTimeline.vue
src/components/timelines/ColorTimeline.vue
src/components/timelines/DenseTimeline.vue
src/components/timelines/IconDotsTimeline.vue
src/components/timelines/IconTimeline.vue
src/components/timelines/OppositeTimeline.vue
src/components/timelines/ReverseTimeline.vue
src/components/timelines/SmallTimeline.vue
src/components/timelines/TimelineItemDefaultTimeline.vue
src/router/index.js
src/views/Timelines.vue

3112-Vuetify-element-Timelines

---

src/components/windows/AccountCreationWindow.vue
src/components/windows/CustomizedArrowsWindow.vue
src/components/windows/OnboardingWindow.vue
src/components/windows/ReverseWindow.vue
src/components/windows/VerticalWindow.vue
src/router/index.js
src/views/Windows.vue

3083-Vuetify-element-Windows

---

src/components/file_inputs/AcceptFileInput.vue
src/components/file_inputs/ChipsFileInput.vue
src/components/file_inputs/ComplexSelectionSlotFileInput.vue
src/components/file_inputs/CounterFileInput.vue
src/components/file_inputs/DenseFileInput.vue
src/components/file_inputs/MultipleFileInput.vue
src/components/file_inputs/PrependIconFileInput.vue
src/components/file_inputs/SelectionFileInput.vue
src/components/file_inputs/ShowSizeFileInput.vue
src/components/file_inputs/ValidationFileInput.vue
src/router/index.js
src/views/FileInputs.vue

3065-Vuetify-element-FileInputs

---

src/components/button_groups/MandatoryButtonGroup.vue
src/components/button_groups/MultipleButtonGroup.vue
src/components/button_groups/RoundedButtonGroup.vue
src/components/button_groups/ToolbarButtonGroup.vue
src/components/button_groups/WYSIWYGButtonGroup.vue
src/router/index.js
src/views/ButtonGroups.vue

3077-Vuetify-element-ButtonGroups

---

src/components/chip_groups/ColumnChipGroup.vue
src/components/chip_groups/FilterResultsChipGroup.vue
src/components/chip_groups/MandatoryChipGroup.vue
src/components/chip_groups/MultipleChipGroup.vue
src/components/chip_groups/ProductCardChipGroup.vue
src/components/chip_groups/ToothbrushCardChipGroup.vue
src/router/index.js
src/views/ChipGroups.vue

3078 vuetify element chip groups

---

src/components/color_pickers/CanvasColorPicker.vue
src/components/color_pickers/ElevationColorPicker.vue
src/components/color_pickers/InputsColorPicker.vue
src/components/color_pickers/ModelColorPicker.vue
src/components/color_pickers/SwatchesColorPicker.vue
src/router/index.js
src/views/ColorPickers.vue

3094 vuetify element color pickers

---

pages/bottom_navigation.js
src/components/BottomNavigation/BottomNavigationDefault.js
src/components/Modal/SimpleModal.js

change buttom to bottom, fix same ids

2959 fix component name, 2960 add variable to ids

---

components/bottom_navigation/HideOnScrollBottomNavigation.vue
components/bottom_navigation/ScrollThresholdBottomNavigation.vue
components/buttons/LoaderButton.vue
components/tooltips/AlignmentTooltips.vue
components/tooltips/ColorTooltips.vue
components/tooltips/SimpleTooltip.vue
pages/Tooltips.vue

Add snackbar for Loader buttons after they have finished loading,
Modify Tooltip texts' to distinguish between them, add aligned and colored tooltips,
Change content when switching tabs using Bottom Navigation

Fix 4083, 4091 and 4094 issues

---

components/buttons/SizingButton.vue
pages/Buttons.vue

Sizing buttons were added to test-site page Buttons.
@vklonin Vladimir, please, review

Task4200 add elements sizing buttons

---

components/pagination/ColorPagination.vue
components/pagination/DarkPagination.vue
pages/Pagination.vue

https://github.com/jdi-testing/jdi-light/issues/4203

4203 Update test site "Pagination" element

---

components/groups/item_groups/ChipsItemGroup.vue

@omega790 Elena, please, review :)

Task4281_Update_test_site_add_maxFeature_to_ChipsItemGroup

---

components/bottom_sheets/ModelBottomSheet.vue
components/bottom_sheets/PersistentBottomSheet.vue
components/bottom_sheets/ScrollableBottomSheet.vue
pages/Bottom-Sheets.vue

fullscreen
hide-overlay
width/max-width
overlay-color
overlay-opacity
scrollable

Task4255_Update_test_site_addFeaturesToBottomSheet

---

components/navigation_drawers/ClippedNavigationDrawer.vue
pages/Navigation-Drawers.vue

4383 navigation-drawers add clipped

---

components/form_inputs/selects/VariousAttributesSelect.vue

Fixed the issues that on changing in the last Select in all previous we could see the same chosen item.
So now it looks correct

Task4288_bugFixInNewAddedSelects

---

components/dialogs/DisabledDialog.vue
components/dialogs/PersistentDialog.vue
pages/Dialogs.vue

open/close delay doesn't work for the moment. Please add the functionality when the bug is fixed on the Vuetify side: https://github.com/vuetifyjs/vuetify/issues/15938 
The 4418 task stays open

4418 Update Dialogs

---

components/groups/windows/ReverseWindow.vue
components/groups/windows/VerticalWindow.vue

v-windows-item disabled attribute doesn't work: https://github.com/vuetifyjs/vuetify/issues/15957

4422 Update windows

---

components/lists/DarkList.vue
components/lists/ElevatedList.vue
components/lists/SubGroupList.vue
pages/Lists.vue

4432 update lists

---

components/form_inputs/checkboxes/VariousAttributesCheckbox.vue
pages/Checkboxes.vue

**Added:**
dense(y/n)
hint(y/n)
persistent-hint(text)
readonly(y/n)
error(y/n)
success(y/n)
background-color(material or css)
**NOTABENE** agreed that 'multiple' is default state of checkbox

Task4359_addNewFeaturesCheckBoxes

---

components/ratings/VariousAttributesRating.vue
pages/Ratings.vue

**Added:**
clearable
open-delay
close-delay
value

Task4344_addNewFeaturesRatings

---

components/form_inputs/text_fields/AutofocusedTextField.vue
components/form_inputs/text_fields/BackgroundColoredTextField.vue
components/form_inputs/text_fields/CustomHeightTextField.vue
components/form_inputs/text_fields/DarkTextField.vue
components/form_inputs/text_fields/ErrorSuccessCountTextField.vue
components/form_inputs/text_fields/ErrorSuccessTextField.vue
components/form_inputs/text_fields/FlatTextField.vue
components/form_inputs/text_fields/LoadingHeightTextField.vue
components/form_inputs/text_fields/LoadingTextField.vue
components/form_inputs/text_fields/PlaceholderTextField.vue
components/form_inputs/text_fields/ReverseTextField.vue
components/form_inputs/text_fields/ValidationTextField.vue
pages/Text-Fields.vue

4304 Update TextFields

---

components/groups/slide_groups/MandatorySlideGroup.vue
pages/Slide-Groups.vue

Added Mandatory slide group to SLIDE GROUPS

Task4141_addMandatorySlideGroup

---

components/tabs/ArrowsOnHoverTabs.vue
components/tabs/DisabledItemTabs.vue
components/tabs/DisabledTabs.vue
components/tabs/HideSliderTabs.vue
components/tabs/HrefTabs.vue
components/tabs/OptionalTabs.vue
pages/Tabs.vue

Tabs:
Tab:
Tab items:
Tab item:

4241 Update Tabs

---

components/dialogs/PersistentDialog.vue

as agreed deleted no-click-animation in Dialog

4418_dialogDeleteNoClickAnimation

---

components/tables/data_tables/DarkTable.vue
components/tables/data_tables/DisabledPaginationTable.vue
components/tables/data_tables/DisabledSortTable.vue
components/tables/data_tables/FixedHeaderTable.vue
components/tables/data_tables/FooterPropsTable.vue
components/tables/data_tables/MustSortTable.vue
pages/Data-Tables.vue

Data table:
Data table header:
Footer:

4270 Update Data Tables

---

components/calendars/DarkCalendar.vue
components/calendars/EventsClickCalendar.vue
components/calendars/MiscDragAndDropCalendar.vue
pages/Calendars.vue

4416 Update Calendars

---

components/groups/windows/DisabledWindowItem.vue
pages/Windows.vue

Feature Windows item 'disabled' is added

4422_windowItemDisabled

---

components/form_inputs/inputs/LoadingInput.vue
components/form_inputs/inputs/ReadonlyInput.vue
components/form_inputs/inputs/SuccessInput.vue

Features for element 'Input' on test-site

4436_inputFeaturesUpdateTestSite

---

components/form_inputs/inputs/ValidateOnBlurInput.vue
pages/Inputs.vue

For 'Inputs' feature 'validate-on-blur' was added

4436_inputValidateOnBlurFeaturesUpdateTestSite

---

components/tables/data_iterators/GroupTableIterator.vue
components/tables/data_iterators/SingleSelectTableIterator.vue
pages/Data-Iterators.vue

Features 'SingleSelect' and 'Group by' were added to Data Iterators

4290 data iterators update site

---

components/groups/slide_groups/MandatorySlideGroup.vue
pages/Slide-Groups.vue

To add DARK theme to slide groups

4298_addSlideGroupDarkTheme

---

components/progress/progress_circular/ColorProgress.vue

text on rotating progresscirculars changes too fast to check, so i added some static text to another massive of progress circulars

added text to check

---

components/form_inputs/autocompletes/AutocompleteAPISearch.vue
components/form_inputs/autocompletes/AutocompleteAsyncItems.vue
components/form_inputs/autocompletes/AutocompleteFilter.vue
components/form_inputs/autocompletes/AutocompleteFunctionality.vue
components/form_inputs/autocompletes/AutocompleteSlots.vue
components/form_inputs/autocompletes/AutocompleteStyle.vue

changed API to another one that works in every vpn zone and added ids to help navigate through elements

autocompletes fix

---

components/tables/data_iterators/LoadingText.vue
components/tables/data_iterators/NoDataText.vue
components/tables/data_iterators/NoResultsText.vue
pages/Data-Iterators.vue

Created NoDataText.vue, NoResults.vue, LoadingText.vue files
New Elements are added to DataIterators page

Task 4705: Add elements on the test-site DataIterators

---

components/calendars/DarkCalendar.vue

Added parameter "weekdays=[0,1,2,3]" to Dark theme calendar for test creation
Added parameter "dark" for disabled darkCalendarTest() (will be enabled after merge)

Dark Calendar change for Calendar tests

---

angular-site/src/app/form-controls/autocomplete/autocomplete.component.html
angular-site/src/app/form-controls/autocomplete/autocomplete.module.ts
angular-site/src/app/form-controls/autocomplete/components/autocomplete-auto-select-active-option/autocomplete-auto-select-active-option.component.html
angular-site/src/app/form-controls/autocomplete/components/autocomplete-auto-select-active-option/autocomplete-auto-select-active-option.component.ts
angular-site/src/app/form-controls/autocomplete/components/autocomplete-disable-ripple/autocomplete-disable-ripple.component.html
angular-site/src/app/form-controls/autocomplete/components/autocomplete-disable-ripple/autocomplete-disable-ripple.component.ts
angular-site/src/app/form-controls/autocomplete/components/autocomplete-hide-single-selection-indicator-option/autocomplete-hide-single-selection-indicator-option.component.html
angular-site/src/app/form-controls/autocomplete/components/autocomplete-hide-single-selection-indicator-option/autocomplete-hide-single-selection-indicator-option.component.ts
angular-site/src/app/form-controls/autocomplete/components/autocomplete-panel-width-option/autocomplete-panel-width-option.html
angular-site/src/app/form-controls/autocomplete/components/autocomplete-panel-width-option/autocomplete-panel-width-option.ts
angular-site/src/app/form-controls/autocomplete/components/autocomplete-plain-input-option/autocomplete-plain-input-option.component.html
angular-site/src/app/form-controls/autocomplete/components/autocomplete-plain-input-option/autocomplete-plain-input-option.component.ts
angular-site/src/app/form-controls/autocomplete/components/autocomplete-position-option/autocomplete-position-option.component.html
angular-site/src/app/form-controls/autocomplete/components/autocomplete-position-option/autocomplete-position-option.component.ts
angular-site/src/app/form-controls/autocomplete/components/mat-autocomplete-option-disabled/mat-autocomplete-option-disabled.component.html
angular-site/src/app/form-controls/autocomplete/components/mat-autocomplete-option-disabled/mat-autocomplete-option-disabled.component.ts

Update testsite: autocomplete element

added autocomplete elements
